.travis.yml, opbeat/contrib/django/client.py, test_requirements/requirements-django-1.2.txt, test_requirements/requirements-django-1.3.txt, tests/contrib/django/django_tests.py
Due to the legacy of pre-1.5 Django not supporting custom user models, we do not rely on `django.contrib.auth` but rather an internal module, which causes problems in error reporting. This should fix the issue by only relying on `django.contrib.auth` when it is actually installed.
=> Only retrieve Django user information if django.contrib.auth is installed

tests/contrib/django/django_tests.py
This will break the test suite on Django 1.3, but 1.3 is going to be dropped with
PR #22
=> removed custom `Settings` context manager in favour of Django's built-in one

opbeat/contrib/django/middleware/__init__.py, opbeat/contrib/django/models.py, opbeat/contrib/django/utils.py, opbeat/contrib/flask/__init__.py, opbeat/utils/__init__.py
I wanted to make the Opbeat module respect Flask environments (Debug = True/False) and also ended up refactoring `disabled_due_to_debug` a bit so it became reusable.
Note: 
I am very much a Python newbie, so bear with any silly mistakes.
Tested with a starter-kit/dummy Flask app.
=> Debug support for Flask and refactor of `disabled_due_to_debug`

opbeat/base.py, tests/client/client_tests.py
this fixes issues with e.g. django-configurations that give us the configuration as
non-string types
=> turn configuration into strings when initializing the client

conftest.py, tests/contrib/django/testapp/__init__.py, tests/contrib/django/testapp/celery.py
it looks like django-celery isn't kept up to date with Django anymore, and we
don't use its functionality anyway
https://github.com/celery/django-celery/issues/391
https://github.com/celery/django-celery/pull/356
=> don't use djcelery for Django 1.8+

opbeat/processors.py, tests/processors/tests.py
This ensures that we don't completely break when the request has non-utf8
data in its request data
=> sanitizer handle non utf8 request data

opbeat/contrib/django/client.py
This fixes #69 -- at least, the one error I've seen so far. I haven't been able to test for full compatibility yet.
=> Updated the template loader import for Django 1.9 compatibility

setup.py
This is mostly copied from wrapt's setup.py. See opbeat/utils/wrapt/LICENSE
for license information
=> added option to disable building wrapt using an environment variable

opbeat/contrib/django/utils.py
Despite what my reading of https://github.com/django/django/blob/62e83c71d2086b91d58c313e46933ef7aa8b6db1/django/template/base.py#L463
says, several bug reports and support tickets indicate that there can indeed be
nodes without tokens. All reported issues seem to involve nodes that invoke
template rendering (either through calling render_to_string in their render
method, or inclusion tags.
I wasn't able to reproduce the actual error yet, hence the unfortunate lack of
tests.
=> ensure that token is not None before accessing its attributes

.travis.yml, Makefile, opbeat/contrib/asyncio/__init__.py, opbeat/contrib/asyncio/client.py, opbeat/handlers/logging.py, opbeat/transport/asyncio.py, setup.cfg, setup.py, test_requirements/requirements-asyncio.txt, tests/asyncio/test_asyncio_client.py, tests/asyncio/test_asyncio_http.py, tox.ini
```bash
pip install opbeat[asyncio]
```
```python
from opbeat.contrib.asyncio import Client
from opbeat.handlers.logging import OpbeatHandler
opbeat_client = Client(
app_id=app_id,
organization_id=organization_id,
secret_token=secret_token,
transport_class='opbeat.transport.asyncio.AsyncioHTTPTransport')
opbeat_handler = OpbeatHandler(opbeat_client, level='ERROR')
logging.getLogger(__name__).addHandler(opbeat_handler)
```
=> Add support for asyncio compatible transport

opbeat/base.py, opbeat/utils/__init__.py, tests/client/client_tests.py
This steps around the issue reported in #103. Unfortunately, the `postfork` signal turned
out to be somewhat unreliable in our case, because often (but not always) it was only
installed _after_ uwsgi already forked, leaving us in a bad state.
=> make sure we use the non-threaded sync transport if we are in the uwsgi master process

opbeat/base.py, tests/client/client_tests.py
You can now pass an empty list to completely disable processors.
=> Make it possible to disable processors.

.travis.yml, setup.py, test_requirements/requirements-base.txt, test_requirements/requirements-python-2.txt, test_requirements/requirements-zerorpc.txt, travis/build_manylinux_wheels.sh, travis/run_docker.sh, travis/run_tests.sh
This allows users on most Linux environments to install Opbeat including
binary dependencies without having to have a compiler installed.
For now, this will just upload the wheels to Github when a commit is
tagged. In the future, we can configure it to automatically upload the
wheels to PyPI.
=> Add support for building manylinux1 binary wheels on Travis CI

setup.py
As the Readme now includes UTF8, we need to enforce encoding for setups where locale are not set to UTF8.
Otherwise, installing gives the following:
Collecting opbeat
Using cached opbeat-3.3.2.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 20, in <module>
File "/tmp/pip-build-q_7mih6e/opbeat/setup.py", line 152, in <module>
long_description=open(os.path.join(os.path.dirname(__file__), 'README.rst')).read(),
File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1459: ordinal not in range(128)
See https://github.com/pypa/sampleproject/blob/master/setup.py for an example.
=> Parse README as UTF-8

opbeat/contrib/flask/__init__.py
I use application dispatching to combine several Flask applications. Without the sender argument I get performance monitoring data in Opbeat for the applications rather than just the ones that Opbeat is initialised on.
=> Only listen to Flask signals for the application that is being initialised

opbeat/base.py, opbeat/contrib/django/models.py, opbeat/contrib/flask/__init__.py, opbeat/traces.py, tests/client/client_tests.py
This make it possible to define a list of regex patterns that
will be matched against the name of transactions in order
to determine if they should be ignored.
=> Initial attempt at a transactions ignore pattern.

.travis.yml, opbeat/contrib/django/management/commands/opbeat.py, opbeat/contrib/django/middleware/__init__.py, test_requirements/requirements-django-1.10.txt, tests/contrib/django/django_tests.py
This adds support for Django 1.10. The two main issues were
* our somewhat hacky way of implementing sub commands for the "opbeat" management command, which stopped working in 1.10
* The [revised middleware system](https://github.com/django/deps/blob/master/final/0005-improved-middleware.rst) in Django 1.10
The first issue was solved by using proper position arguments with argparse. I also switched to use `call_command` instead of instantiating a command object and calling it directly.
To support new-style middleware, we need to inherit from the new `MiddlewareMixin`. This makes the middleware classes work in both scenarios.
One unfortunate effect of the new middleware system is that we have less insight what is going on inside the middleware. There is no way (AFAICT) to tell if a …
=> Support for Django 1.10

opbeat/base.py
While this error message is google-able, It doesn't need to be so vague.
=> Updating message to indicate that the message is coming from Opbeat

opbeat/base.py, opbeat/conf/defaults.py, opbeat/transport/http_urllib3.py, setup.py, test_requirements/requirements-base.txt, tests/client/client_tests.py, tests/contrib/django/django_tests.py, tests/transports/test_urllib3.py
This is an import of https://github.com/opbeat/opbeat_python_urllib3, which proofed itself to be more stable and less problematic than the urllib2 based transport. It adds two runtime dependencies, urllib3 and certifi, as well as a test-dependency, urllib3-mock.
=> urllib3 transport

opbeat/instrumentation/packages/dbapi2.py, tests/instrumentation/psycopg2_tests.py
This ensures that we trace SQL queries even if the opbeat transaction
starts after the connection has been created.
=> always return a proxied connection from DbApi2Instrumentation subclasses

opbeat/instrumentation/packages/dbapi2.py, opbeat/instrumentation/packages/mysql.py, tests/instrumentation/psycopg2_tests.py
This includes the fix from @jordiecometrica as well as a test case and a slightly reworked `postgres_connection` fixture that cleans up after itself
=> dbapi fixes

opbeat/instrumentation/packages/dbapi2.py
The Python DB API doesn't seem to work, at least with Django and
Postgres, if you call `execute(sql, ())`. This stack traces trying to
index into the empty param tuple. The signature of the function,
according to PEP 249, is
.execute ( operation [, parameters ])
so if there are no parameters, execute should be called without that
variable.
=> properly trace paramless `execute` SQL call (#135)

opbeat/traces.py, test_requirements/requirements-base.txt
=> Don't store `transaction` on `trace` object, as the latter might be shared amongst threads

opbeat/contrib/django/client.py
Django throws `DisallowedHost` when using
`request.build_absolute_uri()`, where the host is not in the
ALLOWED_HOSTS setting.
This prevents Opbeat then from logging the event properly.
Ref: https://code.djangoproject.com/ticket/27506
=> Django: use request.get_raw_uri to work around DisallowedHost

.gitignore, opbeat/instrumentation/packages/botocore.py, opbeat/instrumentation/packages/requests.py, opbeat/instrumentation/register.py, test_requirements/requirements-base.txt, tests/instrumentation/botocore_tests.py, tests/instrumentation/requests_tests.py
This patch adds instrumentation for the AWS SDK (`boto3`/`botocore`), and improves the coverage of `requests` instrumentation in order to pick up `PreparedRequests` sent directly on a lower level.
This patch improved the coverage of our performance report significantly.
=> Botocore instrumentation and improved requests coverage

setup.py
So that it's reflected on the badge in the README
=> Add Py 3.5 and 3.6 trove classifiers in setup.py

.travis.yml, conftest.py, opbeat/contrib/django/client.py, opbeat/contrib/django/middleware/__init__.py, test_requirements/requirements-base.txt, test_requirements/requirements-django-2.0.txt, tests/contrib/django/django_tests.py, tests/contrib/django/testapp/middleware.py, tests/instrumentation/django_tests/template_tests.py
This fixes all known Django 2.0 incompatibilities. It mostly affected our test suite due to `MIDDLEWARE_CLASSES` being gone.
=> fix Django 2.0 incompatibilities
